### ISSUE TITLE
[BUG]: Issues with document browser

### ISSUE THREAD

**Issue by mariodedapolito** [arol-polito/AROL-CLOUD#12]
### Description of the bug

During usage of the web app by the SDP students (thanks Group 9) the following issues were encountered with the document browser and its functionalities.

1. Rename functionality for folders and files is buggy (both BE and FE bugs)
2. When renaming folders, the prompt adds .pdf extension automatically. This should only happen for files (FE issue)
3. Upload functionality is buggy, especially for the first document upload (BE issue)

### Steps To Reproduce

Please view above

**Comment by gmacario** [comment]
> During usage of the web app by the SDP students (thanks Group 9)

I would encourage students to submit Bug Reports directly upstream - maybe after a quick check with yourself
