### ISSUE TITLE
[FEAT]: Add branch protection to main

### ISSUE THREAD

**Issue by mariodedapolito** [arol-polito/AROL-CLOUD#16]
### Description

Add branch protection to main.

**Comment by mariodedapolito** [comment]
Added the following branch restrictions to main:

- Require a pull request before merging
- Require at lest 1 approval before merging
- Require the following status checks to pass before merging:
    1.  Run eslint
    2.  Check docker container
    3.  Check typescript

@gmacario @arol-varesi

**Comment by gmacario** [comment]
> Added the following branch restrictions to main:

Makes a lot of sense. Thanks for taking care of it!
