### ISSUE TITLE
[BUG]: Manage security alerts reported by dependabot

### ISSUE THREAD

**Issue by gmacario** [arol-polito/AROL-CLOUD#17]
### Description of the bug

As part of regular code maintenance I would advise @mariodedapolito to review Dependabot vulnerability alerts and act accordingly.

As a target we should ensure that there are no vulns marked "High" and should strive to minimize those with Moderate or Low score.

### Steps To Reproduce

1. Go to https://github.com/arol-polito/AROL-CLOUD/security/dependabot (accessible only to maintainer)
2. Review the vulnerability report (1 High and 8 Moderate as of today)

**Comment by mariodedapolito** [comment]
@gmacario on it! Thank you for reporting!
