### ISSUE TITLE
Fix bugs created from lint ticket modifications

### ISSUE THREAD

**Issue by mariodedapolito** [arol-polito/AROL-CLOUD#7]
In order to pass all lint checks, both FE and BE code were refactored. During this refactoring several bugs were introduced, mainly in the FE due to changes in the useEffect deps.

**Comment by mariodedapolito** [comment]
@gmacario @arol-varesi a quick update on progress and work done this week:

1. issues introduced by lint changes (mainly in the dashboard) have been fixed and the project runs ok now
2. since i had to fix useEffect dependencies on the dashboard i took the chance to refactor the whole dashboard feature by introducing custom hooks which increase the code readability and also had a shot at optimizing the dashboard performance. The results of the optimization work are fantastic with performance (rendering time) uplifts of up to 25x.
3. resolved some issues and conflicts between react and the linter in the package.json

Note: the lint run of the last commit is failing due to some debugging code and some WIP performance optimization features.

**Comment by mariodedapolito** [comment]
@gmacario @arol-varesi 
Linting resolved and some other bugs also resolved. Also a complex BE (impacted mongoDB version of app only) was also squashed. Please do not merge yet as I need another couple of days to test and resolve bugs as the changes introduced by this PR are pretty drastic.

**Comment by gmacario** [comment]
> @gmacario @arol-varesi Linting resolved and some other bugs also resolved. Also a complex BE (impacted mongoDB version of app only) was also squashed.

Thank you for the good news @mariodedapolito!

> Please do not merge yet as I need another couple of days to test and resolve bugs as the changes introduced by this PR are pretty drastic.

OK, will wait for your input then

**Comment by mariodedapolito** [comment]
@gmacario @arol-varesi PR for this issue up.
