### ISSUE TITLE
Workaround for `npm install --force` for the FE

### ISSUE THREAD

**Issue by gmacario** [arol-polito/AROL-CLOUD#8]
_Originally posted by @mariodedapolito in https://github.com/arol-polito/AROL-CLOUD/issues/6#issuecomment-1677336131_

> We need the `npm install --force` for the FE as the library which we are using for some dashboard gauges is creating some conflicts with other deps. I will try to find a workaround for this problem and keep using npm.

**Comment by gmacario** [comment]
@mariodedapolito is this somewhat related to the error @arol-varesi and myself noticed in https://github.com/arol-polito/AROL-CLOUD/pull/10#issuecomment-1691262984 ?

**Comment by mariodedapolito** [comment]
@gmacario this issue was resolved by #7. Now `--force` flag is not necessary anymore. Marking this as closed. Thank you!

cc @arol-varesi
