### ISSUE TITLE
[FEAT]:  Add security policy

### ISSUE THREAD

**Issue by gmacario** [arol-polito/AROL-CLOUD#9]
### Description

From https://github.com/arol-polito/AROL-CLOUD/security (in incognito mode)

![image](https://github.com/arol-polito/AROL-CLOUD/assets/75182/7a53fc1b-2655-4182-9b03-fecd19d8740e)

**Comment by mariodedapolito** [comment]
@gmacario PR up with security policy.

**Comment by gmacario** [comment]
> @gmacario PR up with security policy.
> 
> #11

Thanks @mariodedapolito I made some comments directly on #11
